version: '2'
services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.10
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer/data:/data

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/sonarr/data:/config
      #- ./media/tvshows:/tv
      - ./media/tvshows:/downloads
    networks:
      default:
        ipv4_address: 172.18.0.13
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:5.14
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/radarr/config:/config
      #- ./media/movies:/movies
      - ./media/movies:/downloads
    networks:
      default:
        ipv4_address: 172.18.0.12
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/lidarr/config:/config
      #- ./media/music:/music
      - ./media/music:/downloads
    networks:
      default:
        ipv4_address: 172.18.0.15
    ports:
      - 8686:8686

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/bazarr/config:/config
      - ./media/movies:/media/movies
      - ./media/tvshows:/media/tvshows
      - ./media/@downloads:/downloads
    networks:
      default:
        ipv4_address: 172.18.0.14
    ports:
      - 6767:6767
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ./volumes/jackett/config:/config
      - ./media/@downloads:/downloads
    networks:
      default:
        ipv4_address: 172.18.0.11
    ports:
      - 9117:9117
    restart: unless-stopped

  plex:
    image: ghcr.io/linuxserver/plex:bionic
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      # - PLEX_CLAIM= #optional
    volumes:
      - ./volumes/plex/library:/config
      - ./media/movies:/media/movies
      - ./media/tvshows:/media/tvshows
      - ./media/music:/media/music
    restart: unless-stopped

  tvheadend:
    image: ghcr.io/linuxserver/tvheadend
    container_name: tvheadend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      #- RUN_OPTS=<run options here> #optional
    volumes:
      - ./volumes/tvheadend/config:/config
      - ./media/TVrecordings:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    # devices:
      #- /dev/dri:/dev/dri #optional
      #- /dev/dvb:/dev/dvb #optional
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ./volumes/deluge/config:/config
      - ./media/movies:/media/movies
      - ./media/tvshows:/media/tvshows
      - ./media/music:/media/music
      - ./media/@downloads/deluge:/downloads
    networks:
      default:
        ipv4_address: 172.18.0.100
    ports:
      - 8112:8112
      - 58846:58846
      - 58946:58946

  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./volumes/nzbget/config:/config
      - ./media/@downloads/nzbget:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16